### PR TITLE
Develop 8

### PR DESCRIPTION
**Pull request by chedman**
open ended other recode

### CODE REVIEW

**Comment by ptatian** [comment]
@chedman Thanks for working on this. I apologize because I should have made it clear what I was expecting. I would have rather you added code to the **Voices_nonopen_recode.sas** SAS program that creates the **Voices.Voices_2017_nonopen_recode** data set. That's my fault for not being clear.

But, I don't want you to redo everything, so here's how I suggest we proceed. Can you modify your STATA program to create a CSV file with the recoded values? This can then be merged with the with the other data in the **Voices_nonopen_recode.sas** program to add those values to the final **Voices.Voices_2017_nonopen_recode** output data set. I'd like to ask you to please make all of those modifications, SAS program included. 

Please let me know if you have any questions or would like to discuss further.

**Comment by chedman** [comment]
@ptatian Sorry i did not the confirm the format beforehand. Yes, i can make those updates to the STATA program and the SAS program. I'll submit another pull request when those updates are complete.

**Comment by ptatian** [comment]
Thanks @chedman. You don't need to submit a new pull request. Any new commits you make will be added to the current pull request. Just @-mention me in the pull request comments when you are ready for me to look at it.

**Comment by ptatian** [comment]
@chedman I think things are getting a bit confused because you are trying to work on two issues at once. Let's focus on one issue at a time and finish it before we move on to the next one. 

So, taking issue #8, we don't want to add Q1 and Q2 to the **Voices_2017_nonopen_recode** data set. You have a data step that is trying to read a non-existent data set, and that's producing an error.

```
477        /*Merge Q1 and Q2 recode*/
478        data Voices_2017_nonopen_recode_3;
479        	merge Voices_2017_nonopen_recode_2 Voices_2017_q1_q2_recode;
ERROR: File WORK.VOICES_2017_Q1_Q2_RECODE.DATA does not exist.
480        	by caseid;
481        run;
```

I removed that code. Later, you have an unnecessary sort.

```
Proc sort data=Voices_2017_nonopen_recode_1 out=Voices_2017_nonopen_recode_2;
	By caseid;
run; 
```

You did a merge of data sets by caseid to create **Voices_2017_nonopen_recode_1**. Therefore, **Voices_2017_nonopen_recode_1** will already be sorted by caseid and there's no need to sort it again.

As a check, I added a Proc Compare to check the current version of the **Voices.Voices_2017_nonopen_recode** data set with the new one we are creating. It made me realize that I made mistake in telling you to drop the variables that were being replaced, because that drops the variable labels and other info, too. So, I changed that. The merge will still replace the info for the common variables with the new data you are importing. 

One question I have: **What are variables Q28_11 and Q63_i?** These seem to be new variables you added, but we need to labeled and format them.

**Comment by ptatian** [comment]
@chedman Also, as a best practice, **please use the pull request/issue conversation for sending questions and messages,** rather than inserting them in the commit description. While I do receive those messages if you @-mention me in the commit description, they aren't as readily accessible since you have to go into each individual commit to see them. Better to put all of the back-and-forth in the conversation tab. Let me know if you have questions.

**Comment by chedman** [comment]
@ptatian Thanks for looking at the programs and for the feedback. Sorry for the confusion around the two open issues. I added labels for those two newly generated variables (Q28_11 and Q63_i) in STATA, but realize they would have lost the labels during the transfer.  The two labels are:
-  label Q28_11 = "Military or job transfer/relocation";
- label Q63_i = "Respondent's age";

I can add the labels and format the variables unless you are in the program now and it is easier for you to do so. I realize we'll also need to add Q63_i to the "3 categories" step in the "dummies" macro.

**Comment by ptatian** [comment]
Thanks, @chedman. I pushed some changes, so you should sync those first. Then you can go ahead and add labels for those variables in the `data Voices_2017_nonopen_recode_1;` data step. You should also add these format statements:

```
   format    Q28_11 Q28_10F.;
   format     Q63_i Q63_H.;
```

Note that, while GfK created separate formats for each variable, they are identical for each variable in the same question so, in this case, it's easier to just reuse a couple of existing formats rather than create new ones. 

I also realized that the Proc Import was creating Q63_i as a character variable, rather than numeric, which would have caused problems when you added it to the dummy generation code. I fixed that by adding the `guessingrows=MAX;` statement, which forces Proc Import to scan the entire file before deciding what variables are numeric or character. 

Also, be aware that you cannot use the `--` operator to say `Q63_a--Q63i`. The `--` operator relies on the order that the variables are **stored** in the data set. Because Q63i is a new variable, it's not in sequence with the other Q63 variables. You can use `Q63_a--Q63h Q63i`, or just list them all individually. (The same doesn't apply to the `-` operator, because that actually relies on the sequence of variable names that end in numbers. More info is available in the [SAS documentation](https://support.sas.com/documentation/cdl/en/lrcon/62955/HTML/default/viewer.htm#a000695105.htm).)

(Honestly, though, I'm not sure we will use Q63_i in the tables because only 9 respondents seem to have mentioned it.)

Once you've made those changes, you should submit the program locally (on D:) and review the Proc Compare output to make sure that the changes are consistent with how you expect them to be. Let me know when that's done.

**Comment by chedman** [comment]
Thanks, @ptatian. I'll get started making those changes now.

**Comment by chedman** [comment]
@ptatian Looking over the totals compared to the other categories I agree that it is probably not worthwhile to keep Q63_i. Should I go back into the STATA program and removing the coding that creates the variable (keeping those responses in other)? I've done spot check reviews of the Proc Compare output and it looks like other figures have been correctly recoded.

**Comment by ptatian** [comment]
@chedman I don’t think you have to go back and change anything. We can just decide whether to include it in the tables later. 

Since everything looks OK, I will go ahead and merge this pull request.

**Comment by ptatian** [comment]
Please do the following to finish up.

- In the GitHub Windows app, switch to the Master branch
- **Sync the changes to your local repo**
- Copy the updated programs to L:
- Batch submit the SAS program on L: (this will replace the data set on L: with the new one)
- Check the log and listing for any problems 

We can then go on to issue #6. Thanks, @chedman.

**Comment by chedman** [comment]
@ptatian - actually I have couple quick questions about the program i was hoping to check in on before finalizing. I think it may be easier to talk through in person/on the phone if you have a moment? Thanks!

**Comment by chedman** [comment]
@ptatian Following up on the strange open ended response entries - I think the issue is an individual took the survey twice. When I was checking through the responses I noticed two entries with identical demographic characteristics, as well as the same sample weight, location, device type, time in residence, and so on. However, the responses on some questions vary between the two entries, including a few opened ended questions. In both cases it looks like they were not just clicking through (i.e. there is no clear pattern in the responses), but, at least with the open ended responses, it looks like one of the entry is more thoughtful/clearly addresses the questions. If you would like to take a look I can send you the two CaseIDs.

**Comment by ptatian** [comment]
Thanks, @chedman  Yes, can you share the two caseid’s? We might want to follow up with GfK to see if they can provide more insight.

**Comment by chedman** [comment]
@ptatian Ok great - the two caseid's are 2289 and 2324. 2289 looks more reliable, at these from my pass through. 

Also, has the new issue been posted? I can commit and create a pull request whenever that this ready. Thanks!

**Pull request merged**
