### PR TITLE
Develop #29

### PR DESCRIPTION
**Pull request by lhendey**
@ptatian - can you review this? on issue #22. I added a data parameter and varlist parameter and a macro loop for voices_tables.sas .  Didn't try more than one data sets.

### CODE REVIEW

**Comment by ptatian** [comment]
@lhendey Looking at this now. Is there a reason you have a loop like this? 

`	%do t=1 %to 1; `

**Comment by lhendey** [comment]
@ptatian yes-  would expand the data and varlist to include multiple data sets (like voices_2017_q1_q2_recode) so would need to loop through to run all the table breaks.

**Comment by ptatian** [comment]
@lhendey OK, I see where you are going but I don't follow how we will insert the new tables into the existing output, then, if we are calling %Make_all_tables() sequentially like that. %Make_all_tables() should create all of the tables on a single invocation. So, I think we need to separate the data prep code from the table generation code. In other words, we need to create the _X_ input data sets that the %Make_one_table()'s need first, and then run all of the tables. 

Let me know if you want to talk further.

**Comment by lhendey** [comment]
@ptatian i see your point.

**Comment by ptatian** [comment]
@lhendey Also, more of a style thing, but the code would be clearer if, instead of using a loop, you just invoked the macro multiple times with parameters, that is, 
```
%Macro Make_all_tables_all_data( dl=, vl= );

			%Make_all_tables( indata=&dl., list=&vl., col=region, colfmt=region., title=Tables for Entire Region )
			%Make_all_tables( indata=&dl., list=&vl., col=geo, colfmt=geo., title=Tables by Jurisdiction )
...
			%Make_all_tables( indata=&dl., list=&vl., col=homeown, colfmt=homeown., title=Tables by Homeownership Status )

	%end;

%mend;

%make_all_tables_all_data( dl=Voices.Voices_2017_nonopen_recode, vl=full_var_list ); 
%make_all_tables_all_data( dl=Voices.Voices_2017_xxx_recode, vl=xxx_var_list );
...
```

Although, based on my previous comment, you may need to rework this, anyway.

**Comment by ptatian** [comment]
@lhendey Sorry, probably I should have thought this through more when I set it up originally.

**Comment by ptatian** [comment]
Modifications complete. Closing issue.

**Pull request merged**
